version: '3.8'

services:
  spotify-telegram-notifier:
    image: spotify-telegram-notifier
    build:
      context: .
    ports:
      - "8081:8080"
    environment:
      SPRING_DATASOURCE_URL: jdbc:postgresql://postgres:5432/telegram-delivery-db
      SPRING_DATASOURCE_USERNAME: telegram-user
      SPRING_DATASOURCE_PASSWORD: telegram-password
      SPRING_DATASOURCE_DRIVER-CLASS-NAME: org.postgresql.Driver
      SPRING_JPA_DATABASE-PLATFORM: org.hibernate.dialect.PostgreSQLDialect
      SPRING_RABBITMQ_HOST: rabbitmq-container
      SPRING_RABBITMQ_USERNAME: guest
      SPRING_RABBITMQ_PASSWORD: guest
      SPRING_RABBITMQ_PORT: 5672
      SPRING_RABBITMQ_VIRTUAL-HOST: spotify_delivery_host
      rabbitmq.exchange: spotify_delivery_exchange
      rabbitmq.queue: telegram_queue
      rabbitmq.routing-key: key_tg
    depends_on:
      - postgres
    networks:
      - shared_network

  postgres:
    image: postgres:15
    environment:
      POSTGRES_USER: telegram-user
      POSTGRES_PASSWORD: telegram-password
      POSTGRES_DB: telegram-delivery-db
    ports:
      - "5433:5432"
    networks:
      - shared_network

networks:
  shared_network:
    external: true